### ISSUE TITLE
 Conflict with InitialHandler

### ISSUE THREAD

**Issue by Leymooo** [WolverinDEV/BungeeUtil#18]
Hi. I has an antibot protection on Map, based on WaterFall.(https://github.com/Dimatert9/Waterfall-rus)
In IntialHandler class i check if player need enter captcha or not(https://github.com/Dimatert9/Waterfall-rus/blob/master/BungeeCord-Patches/0042-add-captcha.patch#L3057-L3060) and if need i set custom Handler.
After installing your plugin this lines was ignored. Always connect player to default server. Can you fix it?

Sorry for bad English :(

**Comment by WolverinDEV** [comment]
Hey,
the problem is that you have an specific BungeeCord (Or a patched BungeeCord). Im currently only supporting the normal version of BungeeCord. Maybe you can add this lines by your self in a own responsetory for you?

Sry for my late response but i had no time to checkout the Internet.

**Comment by Leymooo** [comment]
I tried to add captcha to default bungeecord(https://github.com/Dimatert9/BungeeCord/commit/dd9e8ce7394e8deacb1c92c0c6cafd2da3ec1e13) and it dont work.
Maybe your plugin has custom handler, when player join?

**Comment by WolverinDEV** [comment]
Yeah i think there are a lots of compatibility problems.
Well first is that im using my own channel inizializer (https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/dev/wolveringer/bungeeutil/netty/ChannelInizializer.java) and im creating an own instalce of n PacketHandler with the super class InitialHandler (https://github.com/WolverinDEV/BungeeUtil/blob/2.0/src/dev/wolveringer/bungeeutil/netty/BungeeUtilChannelInizializer.java#L104)
Well, i think it will be impossible that this two applications work together.

**Comment by Leymooo** [comment]
why i cant compile your plugin?
http://pastebin.com/K2QnAYpX
if i change this symbol
http://pastebin.com/XFGpEW0A

**Comment by WolverinDEV** [comment]
Huh this errors sounds funny.
Well the first is only the harset error. Change the charset to UTF-8 then all should work.
The problem with the second error i realy dont know what this means xD i never saw somethink like that before. Maybe try to google?

**Comment by Leymooo** [comment]
Google dont help me((
Can you try compile with changed IIItialHandler?
http://dropmefiles.com/cVegR
Maybe you need be add BungeeCord-Protocol to pom.xml.
 Thanks.

**Comment by WolverinDEV** [comment]
Your files didnt contains a pom.xml so i cant compile this.
Well i thnk the main problem is the charset. You try to compile all sources with Cp1251 but all files are encoded in UTF-8.

**Comment by Leymooo** [comment]
you can put this files to src\main\java and they must will compile. need only add BungeeCord-Protocol module.
I change cp1251 to utf8 and first error gone. but "cannot find symbol" is not fixed.

**Comment by Leymooo** [comment]
tried compile on VDS.
http://pastebin.com/5yyg4WPq

**Comment by WolverinDEV** [comment]
Hey i dont know what VDS is, but did you cloned my build of BungeeCord ad typed mvn install?
I know that when you have installed that then all should work. I tested it on a brand new vm. And hmm the charset problem sounds a littlebit funny. But however.

And why is BungeeCord-Protocol  depend? I never use somethink from this?

**Comment by Leymooo** [comment]
Antibot protection based on packets. and this packets use Bungee-protocol imports.
VDS - this is virtual dedicated server.
http://pastebin.com/DvuARtrt

**Comment by WolverinDEV** [comment]
Well i dont have time currently so,
but i googled a quick time and found a interristing issue with has equals problems: https://github.com/jhipster/jhipster-uml/issues/66 Not shure if this helping but maybe. I will take a look later

**Comment by Leymooo** [comment]
I fixed "cannot find symbol" but what wrong now? 
http://pastebin.com/6tsn0e14

**Comment by WolverinDEV** [comment]
```
XXX cannot find symbol
  symbol:   class Getter
  location:  XXX
```
I still dont know what this error course...
I realy have no plan. Maybe try to compile it on a unix based system (maybe ubuntu or debian?)

**Comment by Leymooo** [comment]
debian
http://pastebin.com/VxELsKw3
udp.
 i found the problem 
![image](https://cloud.githubusercontent.com/assets/8667294/21701150/ba8a1d62-d3ac-11e6-94ec-a7bf8e9a9624.png)
Folder "string" need be in terminal folder. But classes in string will be has wrong package.

**Comment by WolverinDEV** [comment]
oh well im an ideot.... yeah i moved locally the package.
You can get the newest version here. https://gitlab.com/WolverinDEV/TerminalUtils
When im at home (in 4 days) i will update it in the Maven Central Repository.

**Comment by Leymooo** [comment]
thanks. now all work.
![image](https://cloud.githubusercontent.com/assets/8667294/21702582/fbd4e7f4-d3b4-11e6-8818-a2f1079f9478.png)

**Comment by Leymooo** [comment]
Moved to #19 
(New issue)

**Comment by WolverinDEV** [comment]
Problem fixed
